#!/bin/zsh
# shellcheck shell=bash
unset IFS
set -eufEo pipefail

meaning_of_life() {
    echo '42'
}

main() {
    echo "Main: The meaning of life is $(meaning_of_life)"
}

# shellcheck disable=SC2154
if [ "${zsh_eval_context[-1]}" = 'toplevel' ]; then
    main
fi
