#!/bin/zsh
# shellcheck shell=bash

meaning_of_life() {
    return 42
}

main() {
    meaning_of_life
    echo "Main: The meaning of life is $?"
}

# shellcheck disable=SC2154
if [ "${zsh_eval_context[-1]}" = 'toplevel' ]; then
    main
fi
