#!/bin/zsh
# shellcheck shell=bash
unset IFS
set -eEuo pipefail

# shellcheck source=/dev/null
. "${0%/*}/modulino"

main() {
    echo "Test: The meaning of life is $(meaning_of_life)"
}

# shellcheck disable=SC2154
if [ "${zsh_eval_context[-1]}" = 'toplevel' ]; then
    main
fi
