#!/bin/ksh
set -euo pipefail
IFS=$'\n\t '

meaning_of_life() {
    return 42
}

main() {
    meaning_of_life
    echo "Main: The meaning of life is $?"
}

if [[ "$0" == */modulino ]]; then
    main
fi
