#!/bin/ksh
unset IFS
set -euo pipefail

# shellcheck source=/dev/null
. "${0%/*}/modulino"

main() {
    echo "Test: The meaning of life is $(meaning_of_life)"
}

if [[ "$0" == */test ]]; then
    main
fi
