#!/usr/bin/env fish

set MEANING_OF_LIFE 42

function main
  echo "Main: The meaning of life is $MEANING_OF_LIFE"
end

#
# string match conditionals may not be combined in fish 2
#

if [ "$_" = */modulino ]
  main
else if [ "$_" = ./*modulino ]
  main
else if [ (echo "$_" | grep 'modulino$') ]
  main
end
