#!/usr/bin/env fish

set -x MEANING_OF_LIFE 42

function main
  echo "Main: The meaning of life is $MEANING_OF_LIFE"
end

# string match conditionals may not be combined in fish 2.0.0
if [ "$_" = */scriptedmain ]
    main
else if [ "$_" = ./*scriptedmain ]
  main
end
