#!/usr/bin/env fish

set path (dirname "$_")
. "$path/modulino"

function main
    echo "Test: The meaning of life is $MEANING_OF_LIFE"
end

#
# string match conditionals may not be combined in fish 2
#

if [ "$_" = */test ]
    main
else if [ "$_" = ./*test ]
    main
else if [ (echo "$_" | grep 'test$') ]
    main
end
