#!/bin/sh
unset IFS
set -euf

path="$(dirname -- "$0")"
# shellcheck source=/dev/null
. "$path/modulino"

main() {
    echo "Test: The meaning of life is $MEANING_OF_LIFE"
}

case "$0" in
*/test)
    main
    ;;
*) ;;
esac
