#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

path="$(dirname -- "$0")"
# shellcheck source=/dev/null
. "$path/modulino"

main() {
    echo "Test: The meaning of life is $MEANING_OF_LIFE"
}

case "$0" in
*/test)
    main
    ;;
*) ;;
esac
