#!/bin/bash
unset IFS
set -eEuo pipefail

meaning_of_life() {
    echo '42'
}

main() {
    echo "Main: The meaning of life is $(meaning_of_life)"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main
fi
