#!/bin/bash
set -eEuo pipefail
IFS=$'\n\t '

# shellcheck source=/dev/null
. "${0%/*}/modulino"

main() {
    meaning_of_life
    echo "Test: The meaning of life is $?"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main
fi
