#!/bin/bash
unset IFS
set -eEuo pipefail

# shellcheck source=/dev/null
. "${0%/*}/modulino"

main() {
    echo "Test: The meaning of life is $(meaning_of_life)"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    main
fi
