#!/usr/bin/env ash
# shellcheck shell=ash
unset IFS
set -eu

meaning_of_life() {
    echo '42'
}

main() {
    echo "Main: The meaning of life is $(meaning_of_life)"
}

case "$0" in
*/modulino)
    main
    ;;
esac
