#!/usr/bin/env ash
# shellcheck shell=ash
unset IFS
set -euf

path="${0%/*}"
# shellcheck source=/dev/null
. "$path/modulino"

main() {
    echo "Test: The meaning of life is $(meaning_of_life)"
}

case "$0" in
*/test)
    main
    ;;
esac
