#!/usr/bin/env ash
# shellcheck shell=ash
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

path="${0%/*}"
# shellcheck source=/dev/null
. "$path/modulino"

main() {
    meaning_of_life
    echo "Test: The meaning of life is $?"
}

case "$0" in
*/test)
    main
    ;;
esac
