#!/usr/bin/env dash
unset IFS
set -euf

# shellcheck source=/dev/null
. "${0%/*}/modulino"

main() {
    echo "Test: The meaning of life is $(meaning_of_life)"
}

case "$0" in
*/test)
    main
    ;;
esac
