#!/usr/bin/env dash
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

# shellcheck source=/dev/null
. "${0%/*}/modulino"

main() {
    meaning_of_life
    echo "Test: The meaning of life is $?"
}

case "$0" in
*/test)
    main
    ;;
esac
