#!/bin/zsh
# shellcheck shell=bash

# shellcheck source=/dev/null
. "${0%/*}/modulino"

main() {
    meaning_of_life
    echo "Test: The meaning of life is $?"
}

# shellcheck disable=SC2154
if [ "${zsh_eval_context[-1]}" = 'toplevel' ]; then
    main
fi
